//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Factory.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DB_Factory.md" +
            "f;Integrated Security=True")]
        public string LocalDB_Connection {
            get {
                return ((string)(this["LocalDB_Connection"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.000.107")]
        public string IP_Printer {
            get {
                return ((string)(this["IP_Printer"]));
            }
            set {
                this["IP_Printer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sistematicaweb.it/files/SE_Factory/doc/")]
        public string Path_URL_Documentazione {
            get {
                return ((string)(this["Path_URL_Documentazione"]));
            }
            set {
                this["Path_URL_Documentazione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sistematicaweb.it/files/SE_Factory/fw/")]
        public string Path_URL_Software {
            get {
                return ((string)(this["Path_URL_Software"]));
            }
            set {
                this["Path_URL_Software"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sistematicaweb.it/files/SE_Factory/images/")]
        public string Path_URL_Images {
            get {
                return ((string)(this["Path_URL_Images"]));
            }
            set {
                this["Path_URL_Images"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Commander")]
        public string Path_URL_Commander {
            get {
                return ((string)(this["Path_URL_Commander"]));
            }
            set {
                this["Path_URL_Commander"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IP_Printer_alwaysprint {
            get {
                return ((bool)(this["IP_Printer_alwaysprint"]));
            }
            set {
                this["IP_Printer_alwaysprint"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.8\\SQLEXPRESS;Initial Catalog=DYOPENG;Persist Security Info=" +
            "True;User ID=sa;Password=aavesp19")]
        public string OPEN_Connection {
            get {
                return ((string)(this["OPEN_Connection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=127.0.0.1;user id=root;persistsecurityinfo=True;sshhostname=10.99.1.1;sshp" +
            "assword=2020_SM-user;sshport=22;sshusername=BeSt_Sistem;database=DB_Factory;pass" +
            "word=BeSt_MYSQL1a")]
        public string DB_FactoryConnectionString {
            get {
                return ((string)(this["DB_FactoryConnectionString"]));
            }
        }
    }
}
