//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Factory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_FactoryEntities : DbContext
    {
        public DB_FactoryEntities()
            : base("name=DB_FactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fam_Prod> Fam_Prod { get; set; }
        public virtual DbSet<Printers> Printers { get; set; }
        public virtual DbSet<Schede> Schede { get; set; }
        public virtual DbSet<Software> Software { get; set; }
    }
}
