//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printers
    {
        public int Id { get; set; }
        public string Prn_Name { get; set; }
        public string Prn_Address { get; set; }
        public bool Prn_Default { get; set; }
        public bool Prn_Active { get; set; }
    }
}
