//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schede
    {
        public int Id { get; set; }
        public string Prod_Sch { get; set; }
        public int Prod_Fam { get; set; }
        public string Prod_Descrizione { get; set; }
        public string Prod_Image_Url { get; set; }
    }
}
