//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public int Id { get; set; }
        public string SW_Code { get; set; }
        public Nullable<int> SW_Fam_Prod { get; set; }
        public string SW_Customer { get; set; }
        public string SW_SchedeCompatibili { get; set; }
        public string SW_Microchip_Code { get; set; }
        public string SW_P_Opt_RF { get; set; }
        public bool SW_P_Opt_Oled { get; set; }
        public bool SW_P_Opt_Accel { get; set; }
        public bool SW_P_Opt_SP { get; set; }
        public bool SW_P_Opt_Buzzer { get; set; }
        public bool SW_P_Opt_Vibracall { get; set; }
        public bool SW_P_Opt_LedTorch { get; set; }
        public bool SW_P_Opt_EmButt { get; set; }
        public bool SW_P_Opt_Use_Backlight { get; set; }
        public bool SW_P_Opt_ShiftPage { get; set; }
        public bool SW_P_Opt_Use_Accel { get; set; }
        public bool SW_P_Opt_Use_SP { get; set; }
        public bool SW_P_Opt_Use_Buzzer { get; set; }
        public bool SW_P_Opt_Use_Vibracall { get; set; }
        public bool SW_P_Opt_Use_LedTorch { get; set; }
        public int SW_P_Opt_MaxPairDevices { get; set; }
        public string SW_R_Opt_RF { get; set; }
        public bool SW_R_Opt_Plug_Exp { get; set; }
        public bool SW_R_Opt_Plug_Ple { get; set; }
        public bool SW_R_Opt_Em_Keyb { get; set; }
        public bool SW_R_Opt_Status_Led { get; set; }
        public bool SW_R_Opt_Ext_Ant { get; set; }
        public bool SW_R_Opt_Can { get; set; }
        public bool SW_R_Opt_Prop_Out { get; set; }
        public decimal SW_R_Opt_TimeOut { get; set; }
        public int SW_R_Opt_Cont_Keys { get; set; }
        public int SW_R_Opt_MaxPairDevices { get; set; }
        public bool SW_R_Opt_ShiftPage { get; set; }
        public int SW_R_Opt_Output_No { get; set; }
        public int SW_R_Opt_Dig_Input_No { get; set; }
        public int SW_R_Opt_Ana_Input_No { get; set; }
        public string SW_Revisioni { get; set; }
        public string SW_Funzionamento { get; set; }
    }
}
